trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
    script: |
      echo "##vso[task.setvariable variable=PATH]$(JAVA_HOME)\bin;$(PATH)"

# Prepare Analysis Configuration task
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'justin-sonarqube' # SonarQube service connection id (found in Azure DevOps)
    scannerMode: 'MSBuild'
    projectKey: 'dotnetcore-sonar-azuredevops'
    projectName: 'dotnetcore-sonar-azuredevops'
    script: |
      echo "${JAVA_HOME}"
      echo "${PATH}"

# sqa_d8c33433e33d7e0c02505d9839ca092fd26eec5c
# Dotnet build task
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'

# Run Code Analysis task
- task: SonarQubeAnalyze@5

# Publish Quality Gate Result task
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'